server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaulZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**