#Application configuration
server:
  port: 8092
  error:
    show-message: always

#To see H2 console in browser
# http://localhost:8092/h2-console
#Enabling H2 console
spring:
  h2:
    console:
      enabled: true
  #====================================
  #DB
  #====================================
  datasource:
    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    className: org.h2.Driver
    platform: h2
    username: marcos
    password:

  #====================================
  #Jpa Hibernate
  #====================================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"



